#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v20
# autospec commit: f35655a
#
Name     : R-ddalpha
Version  : 1.3.16
Release  : 67
URL      : https://cran.r-project.org/src/contrib/ddalpha_1.3.16.tar.gz
Source0  : https://cran.r-project.org/src/contrib/ddalpha_1.3.16.tar.gz
Summary  : Depth-Based Classification and Calculation of Data Depth
Group    : Development/Tools
License  : GPL-2.0
Requires: R-ddalpha-lib = %{version}-%{release}
Requires: R-BH
Requires: R-Rcpp
Requires: R-geometry
Requires: R-robustbase
Requires: R-sfsmisc
BuildRequires : R-BH
BuildRequires : R-Rcpp
BuildRequires : R-geometry
BuildRequires : R-robustbase
BuildRequires : R-sfsmisc
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package lib
Summary: lib components for the R-ddalpha package.
Group: Libraries

%description lib
lib components for the R-ddalpha package.


%prep
%setup -q -n ddalpha
pushd ..
cp -a ddalpha buildavx2
popd
pushd ..
cp -a ddalpha buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1727793608

%install
export SOURCE_DATE_EPOCH=1727793608
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/ddalpha/CITATION
/usr/lib64/R/library/ddalpha/DESCRIPTION
/usr/lib64/R/library/ddalpha/INDEX
/usr/lib64/R/library/ddalpha/Meta/Rd.rds
/usr/lib64/R/library/ddalpha/Meta/data.rds
/usr/lib64/R/library/ddalpha/Meta/features.rds
/usr/lib64/R/library/ddalpha/Meta/hsearch.rds
/usr/lib64/R/library/ddalpha/Meta/links.rds
/usr/lib64/R/library/ddalpha/Meta/nsInfo.rds
/usr/lib64/R/library/ddalpha/Meta/package.rds
/usr/lib64/R/library/ddalpha/NAMESPACE
/usr/lib64/R/library/ddalpha/R/ddalpha
/usr/lib64/R/library/ddalpha/R/ddalpha.rdb
/usr/lib64/R/library/ddalpha/R/ddalpha.rdx
/usr/lib64/R/library/ddalpha/data/baby.txt.gz
/usr/lib64/R/library/ddalpha/data/banknoten.txt.gz
/usr/lib64/R/library/ddalpha/data/biomed.txt.gz
/usr/lib64/R/library/ddalpha/data/bloodtransfusion.txt.gz
/usr/lib64/R/library/ddalpha/data/breast_cancer_wisconsin.txt.gz
/usr/lib64/R/library/ddalpha/data/bupa.txt.gz
/usr/lib64/R/library/ddalpha/data/chemdiab_1vs2.txt.gz
/usr/lib64/R/library/ddalpha/data/chemdiab_1vs3.txt.gz
/usr/lib64/R/library/ddalpha/data/chemdiab_2vs3.txt.gz
/usr/lib64/R/library/ddalpha/data/cloud.txt.gz
/usr/lib64/R/library/ddalpha/data/crabB_MvsF.txt.gz
/usr/lib64/R/library/ddalpha/data/crabF_BvsO.txt.gz
/usr/lib64/R/library/ddalpha/data/crabM_BvsO.txt.gz
/usr/lib64/R/library/ddalpha/data/crabO_MvsF.txt.gz
/usr/lib64/R/library/ddalpha/data/crab_BvsO.txt.gz
/usr/lib64/R/library/ddalpha/data/crab_MvsF.txt.gz
/usr/lib64/R/library/ddalpha/data/cricket_CvsP.txt.gz
/usr/lib64/R/library/ddalpha/data/diabetes.txt.gz
/usr/lib64/R/library/ddalpha/data/ecoli_cpvsim.txt.gz
/usr/lib64/R/library/ddalpha/data/ecoli_cpvspp.txt.gz
/usr/lib64/R/library/ddalpha/data/ecoli_imvspp.txt.gz
/usr/lib64/R/library/ddalpha/data/gemsen_MvsF.txt.gz
/usr/lib64/R/library/ddalpha/data/geneexp.rda
/usr/lib64/R/library/ddalpha/data/glass.txt.gz
/usr/lib64/R/library/ddalpha/data/groessen_MvsF.txt.gz
/usr/lib64/R/library/ddalpha/data/growth.rda
/usr/lib64/R/library/ddalpha/data/haberman.txt.gz
/usr/lib64/R/library/ddalpha/data/heart.txt.gz
/usr/lib64/R/library/ddalpha/data/hemophilia.txt.gz
/usr/lib64/R/library/ddalpha/data/indian_liver_patient_1vs2.txt.gz
/usr/lib64/R/library/ddalpha/data/indian_liver_patient_FvsM.txt.gz
/usr/lib64/R/library/ddalpha/data/iris_setosavsversicolor.txt.gz
/usr/lib64/R/library/ddalpha/data/iris_setosavsvirginica.txt.gz
/usr/lib64/R/library/ddalpha/data/iris_versicolorvsvirginica.txt.gz
/usr/lib64/R/library/ddalpha/data/irish_ed_MvsF.txt.gz
/usr/lib64/R/library/ddalpha/data/kidney.txt.gz
/usr/lib64/R/library/ddalpha/data/medflies.rda
/usr/lib64/R/library/ddalpha/data/pima.txt.gz
/usr/lib64/R/library/ddalpha/data/plasma_retinol_MvsF.txt.gz
/usr/lib64/R/library/ddalpha/data/population.rda
/usr/lib64/R/library/ddalpha/data/population2010.rda
/usr/lib64/R/library/ddalpha/data/segmentation.txt.gz
/usr/lib64/R/library/ddalpha/data/socmob_IvsNI.txt.gz
/usr/lib64/R/library/ddalpha/data/socmob_WvsB.txt.gz
/usr/lib64/R/library/ddalpha/data/tae.txt.gz
/usr/lib64/R/library/ddalpha/data/tecator.rda
/usr/lib64/R/library/ddalpha/data/tennis_MvsF.txt.gz
/usr/lib64/R/library/ddalpha/data/tips_DvsN.txt.gz
/usr/lib64/R/library/ddalpha/data/tips_MvsF.txt.gz
/usr/lib64/R/library/ddalpha/data/uscrime_SvsN.txt.gz
/usr/lib64/R/library/ddalpha/data/vertebral_column.txt.gz
/usr/lib64/R/library/ddalpha/data/veteran_lung_cancer.txt.gz
/usr/lib64/R/library/ddalpha/data/vowel_MvsF.txt.gz
/usr/lib64/R/library/ddalpha/data/wine_1vs2.txt.gz
/usr/lib64/R/library/ddalpha/data/wine_1vs3.txt.gz
/usr/lib64/R/library/ddalpha/data/wine_2vs3.txt.gz
/usr/lib64/R/library/ddalpha/help/AnIndex
/usr/lib64/R/library/ddalpha/help/aliases.rds
/usr/lib64/R/library/ddalpha/help/ddalpha.rdb
/usr/lib64/R/library/ddalpha/help/ddalpha.rdx
/usr/lib64/R/library/ddalpha/help/paths.rds
/usr/lib64/R/library/ddalpha/html/00Index.html
/usr/lib64/R/library/ddalpha/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/ddalpha/libs/ddalpha.so
/V4/usr/lib64/R/library/ddalpha/libs/ddalpha.so
/usr/lib64/R/library/ddalpha/libs/ddalpha.so
